CREATE DATABASE CAMDO

USE CAMDO

CREATE TABLE VAITRO(
	MaVaiTro INT PRIMARY KEY,
	Ten NVARCHAR(max)
)

CREATE TABLE TAIKHOAN(
	MaTaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
	TenNhanVien NVARCHAR(max),
	TenTaiKhoan NVARCHAR(100),
	MatKhau NVARCHAR(max),
	MaVaiTro INT not null
	
	FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro)
)

CREATE TABLE KHACHHANG(
	MaKhachHang NVARCHAR(10) PRIMARY KEY,
	TenKhachHang NVARCHAR(MAX),
	SDT NVARCHAR(20),
	CMND NVARCHAR(12)
)

CREATE TABLE HOADON(
	MaHoaDon INT IDENTITY(1,1) PRIMARY KEY,
	MaKhachHang NVARCHAR(10) NOT NULL,
	Ngay SMALLDATETIME

	FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang),
)

CREATE TABLE CT_HOADON(
	MaCT_HoaDon INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MaHoaDon INT,
	TenVatTu NVARCHAR(MAX) NOT NULL,
	SoLuong INT,
	GiaCam INT,
	GiaChuoc INT,
	HanChot SMALLDATETIME,
	TongTien INT

	FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon)
)


CREATE TABLE BAOCAODOANHSO (
	MaBCDS			INT IDENTITY (1, 1),
	ThoiGian		SMALLDATETIME, -- ngay minh muon xem bao cao doanh so
	TongDoanhThu	MONEY DEFAULT 0

	CONSTRAINT BAOCAODOANHSO_PK PRIMARY KEY (MaBCDS)
)

CREATE TABLE CT_BCDS (
	MaBCDS	INT PRIMARY KEY,
	SoLuotSua	INT DEFAULT 0,
	ThanhTien	MONEY DEFAULT 0,
	TiLe		VARCHAR(MAX)

	FOREIGN KEY (MaBCDS) REFERENCES BAOCAODOANHSO(MaBCDS)
)

CREATE TABLE THUTIEN ( 
	MaThuTien INT IDENTITY(1,1) PRIMARY KEY,
	MaHoaDon INT,
	NgayThuTien SMALLDATETIME,
	SoTienThu INT

	FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon)
)

SET DATEFORMAT DMY

ALTER DATABASE SCOPED CONFIGURATION 
  SET VERBOSE_TRUNCATION_WARNINGS = ON;

INSERT INTO VAITRO VALUES (0, 'staff')
INSERT INTO VAITRO VALUES (1, 'admin')

INSERT INTO TAIKHOAN (TenTaiKhoan, MatKhau, MaVaiTro) VALUES ('staff', 'staff', 0)
INSERT INTO TAIKHOAN (TenTaiKhoan, MatKhau, MaVaiTro) VALUES ('admin', 'admin', 1)

INSERT INTO KHACHHANG (MaKhachHang,TenKhachHang, SDT, CMND) VALUES ('DMT','Duong Minh Thai','0703174619', '079202003767')
INSERT INTO KHACHHANG (MaKhachHang,TenKhachHang, SDT, CMND) VALUES ('CDQ','Can Duc Quang','0868331239', '079202002343')
INSERT INTO KHACHHANG (MaKhachHang,TenKhachHang, SDT, CMND) VALUES ('CVS','Chau Vinh Sinh','0916056985', '079202006979')

INSERT INTO HOADON (MaKhachHang,Ngay) VALUES ('DMT','1/12/2022')
INSERT INTO HOADON (MaKhachHang,Ngay) VALUES ('CDQ','3/12/2022')
INSERT INTO HOADON (MaKhachHang,Ngay) VALUES ('CVS','4/12/2022')

INSERT INTO CT_HOADON (MaHoaDon, TenVatTu, SoLuong, GiaCam, GiaChuoc) VALUES (1, N'Xe may', 1, '50000000','60000000')
INSERT INTO CT_HOADON (MaHoaDon, TenVatTu, SoLuong, GiaCam, GiaChuoc) VALUES (2, N'Laptop', 1, '25000000','30000000')
INSERT INTO CT_HOADON (MaHoaDon, TenVatTu, SoLuong, GiaCam, GiaChuoc) VALUES (2, N'Dien thoai', 1, '10000000','11000000')
INSERT INTO CT_HOADON (MaHoaDon, TenVatTu, SoLuong, GiaCam, GiaChuoc) VALUES (3, N'Dong ho', 1, '5000000','6000000')
INSERT INTO CT_HOADON (MaHoaDon, TenVatTu, SoLuong, GiaCam, GiaChuoc) VALUES (3, N'Day chuyen', 1, '3000000','4000000')
INSERT INTO CT_HOADON (MaHoaDon, TenVatTu, SoLuong, GiaCam, GiaChuoc) VALUES (3, N'May tinh bang', 1, '20000000','21000000')

