//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamDo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public int MaCT_HoaDon { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public string TenVatTu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaThamDinh { get; set; }
        public Nullable<int> LaiSuat { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
