//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamDo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAP
    {
        public string MaVatTu { get; set; }
        public string MaPhieuNhap { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiaTra { get; set; }
        public string TrangThai { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
