//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamDo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUTIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUTIEN()
        {
            this.CT_THUTIEN = new HashSet<CT_THUTIEN>();
        }
    
        public int MaThuTien { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayThuTien { get; set; }
        public Nullable<int> SoTienThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_THUTIEN> CT_THUTIEN { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
